import React from "react";

function WindandSolar() {
  return (
    <div className="mx-auto px-[30px] md:px-[60px] lg:px-[80px] xl:px-[100px] mt-[10px]">
      <div className="flex flex-col justify-center items-center h-full overflow-hidden xs:py-[20px] lg:py-[50px]">
        <div className=" ">
          <div className="text-center container ">
            <h2 className="text-[#316D69]  pb-[15px] md:pb-[20px] leading-7 tracking-normal font-montserrat font-bold text-3xl ">
              Wind <span className="text-[#bab220]">/</span> Solar
            </h2>
            <p className="text-[14px] md:text-[16px] lg:text-lg font-normal text-[#3c3c3c] font-poppins leading-7 ">
              Wind and solar energy are two renewable sources of power that have
              started to become much more popular due to their potential for
              making a positive environmental impact. Both solar and wind energy
              can be used to generate electricity efficiently, reduce dependence
              on fossil fuels, and have fewer associated emissions than other
              types of energy production.
            </p>
            <p className="text-[14px] md:text-[16px] lg:text-lg font-normal text-[#3c3c3c] ">
              Solar energy is generated by capturing solar radiation from the
              sun and converting it into usable electricity through solar panels
              or solar cells. Wind energy is produced by using wind turbines to
              capture kinetic energy from the movement of air and transforming
              it into usable electricity.
            </p>
            <p className="text-[14px] md:text-[16px] lg:text-lg font-normal text-[#3c3c3c] ">
              As our reliance on solar and wind grows, it will help ensure a
              more environmentally friendly future for generations to come.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default WindandSolar;
